[package]
name = "lambda_twist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lambda_twist"
crate-type = ["rlib"]

[dependencies]
nalgebra = "*"